controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: false
    rover_base_controller:
      type: diff_drive_controller/DiffDriveController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

rover_base_controller:
  ros__parameters:
    left_wheel_names: [front_left_wheel_joint, rear_left_wheel_joint]
    right_wheel_names: [front_right_wheel_joint, rear_right_wheel_joint]
    wheels_per_side: 2
    wheel_separation: 0.41
    wheel_radius: 0.11
    cmd_vel_timeout: 0.5
    publish_rate: 50.0
    base_frame_id: base_link
    odom_frame_id: odom
    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.003]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.003]
    use_stamped_vel: false
    enable_odom_tf: true
    publish_wheel_data: true
    open_loop: true
    velocity_rolling_window_size: 10

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false 
